name: Parker deployment

on:
  push:
    branches:
      - trunk

permissions:
  contents: write

jobs:
  deploy-parker:
    name: Deploy Parker-code to "parker-deploy" branch
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up git
        run: |
          git config --global user.email "parker-deploy@example.com"
          git config --global user.name "parker-deploy GitHub Action"
      - name: Deploy code
        run: |
          CURR_DIR=$(pwd)
          tar -zcvf /tmp/p.tar.gz -C parker/ . && \
          git pull && \
          git checkout -b parker-deploy && \
          git pull && \
          rm -rf "$CURR_DIR/*" && \
          tar -zxvf /tmp/p.tar.gz && \
          git status && \
          git commit -a -m 'Deploying to "parker-deploy" branch' . && \
          git push --set-upstream origin parker-deploy
