name: Parker deployment

on:
  push:
    branches:
      - trunk

permissions:
  contents: write

jobs:
  deploy-parker:
    name: Deploy Parker-code to "parker-deploy" branch
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4    
      - name: Deploy code
        run: |
          find .
          CURR_DIR=$(pwd)
          tar -zcvf /tmp/p.tar.gz -C parker/ . && \
          git checkout -b parker-deploy && \
          rm -rf "$CURR_DIR/*" && \
          tar -zxvf /tmp/p.tar.gz && \
          git status && \
          git commit -m 'Deploying to "parker-deploy" branch' .
