name: Parker deployment

on:
  push:
    branches:
      - trunk

permissions:
  contents: write

jobs:
  deploy-parker:
    name: Deploy Parker-code to "parker-deploy" branch
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main-code
      - name: Checkout "parker-deploy
        uses: actions/checkout@v4
        with:
          path: parker-deploy
          ref: parker-deploy
      - name: Configure git for commits
        run: |
          git config --global user.email "{user.id}+{user.login}@users.noreply.github.com"
          git config --global user.name "parker-deploy GitHub Action"
      - name: Deploy code
        run: |
          CURR_DIR=$(pwd)
          find . && \
          rsync -av --delete --exclude ".git/*" "$CURR_DIR/main-code/parker/." "$CURR_DIR/parker-deploy/." && \
          pushd "$CURR_DIR/parker-deploy" && \
          git status && \
          date +%s > timestamp.txt && \
          git commit -a -m 'Deploying to "parker-deploy" branch' . && \
          git push --set-upstream origin parker-deploy
